import json

# Comprehensive real interview questions bank - 50 questions covering all major DSA topics
# These are the most commonly asked questions at FAANG and top tech companies

questions = [
    # ===== ARRAYS & HASHING =====
    {"id":1,"title":"Two Sum","type":"Programming","category":"Arrays / Hashing","difficulty":"Easy","companies":["Google","Amazon","Meta","Apple"],"statement":"Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.","examples":[{"input":"nums = [2,7,11,15], target = 9","output":"[0,1]","explanation":"Because nums[0] + nums[1] == 9, we return [0, 1]."},{"input":"nums = [3,2,4], target = 6","output":"[1,2]","explanation":"nums[1] + nums[2] == 6."}],"constraints":["2 <= nums.length <= 10^4","-10^9 <= nums[i] <= 10^9","Only one valid answer exists."],"python_solution":"class Solution:\n    def twoSum(self, nums, target):","java_solution":"class Solution {\n    public int[] twoSum(int[] nums, int target) {\n    }\n}","test_cases":[{"input":"[2,7,11,15], 9","expected":"[0, 1]"},{"input":"[3,2,4], 6","expected":"[1, 2]"}],"explanation":""},
    {"id":2,"title":"Best Time to Buy and Sell Stock","type":"Programming","category":"Arrays","difficulty":"Easy","companies":["Amazon","Google","Meta","Goldman Sachs"],"statement":"You are given an array prices where prices[i] is the price of a given stock on the ith day.\n\nYou want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.\n\nReturn the maximum profit you can achieve. If you cannot achieve any profit, return 0.","examples":[{"input":"prices = [7,1,5,3,6,4]","output":"5","explanation":"Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5."},{"input":"prices = [7,6,4,3,1]","output":"0","explanation":"No profitable transaction possible."}],"constraints":["1 <= prices.length <= 10^5","0 <= prices[i] <= 10^4"],"python_solution":"class Solution:\n    def maxProfit(self, prices):","java_solution":"class Solution {\n    public int maxProfit(int[] prices) {\n    }\n}","test_cases":[{"input":"[7,1,5,3,6,4]","expected":"5"},{"input":"[7,6,4,3,1]","expected":"0"}],"explanation":""},
    {"id":3,"title":"Contains Duplicate","type":"Programming","category":"Arrays / Hashing","difficulty":"Easy","companies":["Amazon","Apple","Adobe"],"statement":"Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.","examples":[{"input":"nums = [1,2,3,1]","output":"true","explanation":"1 appears twice."},{"input":"nums = [1,2,3,4]","output":"false","explanation":"All elements are distinct."}],"constraints":["1 <= nums.length <= 10^5","-10^9 <= nums[i] <= 10^9"],"python_solution":"class Solution:\n    def containsDuplicate(self, nums):","java_solution":"class Solution {\n    public boolean containsDuplicate(int[] nums) {\n    }\n}","test_cases":[{"input":"[1,2,3,1]","expected":"True"},{"input":"[1,2,3,4]","expected":"False"}],"explanation":""},
    {"id":4,"title":"Product of Array Except Self","type":"Programming","category":"Arrays","difficulty":"Medium","companies":["Amazon","Facebook","Microsoft","Apple"],"statement":"Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].\n\nYou must write an algorithm that runs in O(n) time and without using the division operation.","examples":[{"input":"nums = [1,2,3,4]","output":"[24,12,8,6]","explanation":"Each element is replaced by the product of all others."},{"input":"nums = [-1,1,0,-3,3]","output":"[0,0,9,0,0]","explanation":"Product with zero consideration."}],"constraints":["2 <= nums.length <= 10^5","-30 <= nums[i] <= 30"],"python_solution":"class Solution:\n    def productExceptSelf(self, nums):","java_solution":"class Solution {\n    public int[] productExceptSelf(int[] nums) {\n    }\n}","test_cases":[{"input":"[1,2,3,4]","expected":"[24, 12, 8, 6]"}],"explanation":""},
    {"id":5,"title":"Maximum Subarray","type":"Programming","category":"Arrays","difficulty":"Medium","companies":["Amazon","Microsoft","LinkedIn","Apple"],"statement":"Given an integer array nums, find the subarray with the largest sum, and return its sum.","examples":[{"input":"nums = [-2,1,-3,4,-1,2,1,-5,4]","output":"6","explanation":"The subarray [4,-1,2,1] has the largest sum 6."}],"constraints":["1 <= nums.length <= 10^5","-10^4 <= nums[i] <= 10^4"],"python_solution":"class Solution:\n    def maxSubArray(self, nums):","java_solution":"class Solution {\n    public int maxSubArray(int[] nums) {\n    }\n}","test_cases":[{"input":"[-2,1,-3,4,-1,2,1,-5,4]","expected":"6"},{"input":"[1]","expected":"1"}],"explanation":""},
    {"id":6,"title":"Maximum Product Subarray","type":"Programming","category":"Arrays","difficulty":"Medium","companies":["Amazon","Google","Microsoft"],"statement":"Given an integer array nums, find a subarray that has the largest product, and return the product.\n\nThe test cases are generated so that the answer will fit in a 32-bit integer.","examples":[{"input":"nums = [2,3,-2,4]","output":"6","explanation":"[2,3] has the largest product 6."},{"input":"nums = [-2,0,-1]","output":"0","explanation":"Cannot get positive product without crossing 0."}],"constraints":["1 <= nums.length <= 2 * 10^4","-10 <= nums[i] <= 10"],"python_solution":"class Solution:\n    def maxProduct(self, nums):","java_solution":"class Solution {\n    public int maxProduct(int[] nums) {\n    }\n}","test_cases":[{"input":"[2,3,-2,4]","expected":"6"},{"input":"[-2,0,-1]","expected":"0"}],"explanation":""},
    {"id":7,"title":"3Sum","type":"Programming","category":"Two Pointers","difficulty":"Medium","companies":["Amazon","Facebook","Google","Microsoft"],"statement":"Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.\n\nNotice that the solution set must not contain duplicate triplets.","examples":[{"input":"nums = [-1,0,1,2,-1,-4]","output":"[[-1,-1,2],[-1,0,1]]","explanation":"Two unique triplets sum to 0."}],"constraints":["3 <= nums.length <= 3000","-10^5 <= nums[i] <= 10^5"],"python_solution":"class Solution:\n    def threeSum(self, nums):","java_solution":"class Solution {\n    public List<List<Integer>> threeSum(int[] nums) {\n    }\n}","test_cases":[{"input":"[0,1,1]","expected":"[]"}],"explanation":""},
    {"id":8,"title":"Container With Most Water","type":"Programming","category":"Two Pointers","difficulty":"Medium","companies":["Amazon","Google","Goldman Sachs"],"statement":"You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).\n\nFind two lines that together with the x-axis form a container, such that the container contains the most water.","examples":[{"input":"height = [1,8,6,2,5,4,8,3,7]","output":"49","explanation":"Max area between index 1 and 8."}],"constraints":["n == height.length","2 <= n <= 10^5","0 <= height[i] <= 10^4"],"python_solution":"class Solution:\n    def maxArea(self, height):","java_solution":"class Solution {\n    public int maxArea(int[] height) {\n    }\n}","test_cases":[{"input":"[1,8,6,2,5,4,8,3,7]","expected":"49"},{"input":"[1,1]","expected":"1"}],"explanation":""},

    # ===== SLIDING WINDOW =====
    {"id":9,"title":"Longest Substring Without Repeating Characters","type":"Programming","category":"Sliding Window","difficulty":"Medium","companies":["Amazon","Google","Facebook","Bloomberg"],"statement":"Given a string s, find the length of the longest substring without repeating characters.","examples":[{"input":"s = 'abcabcbb'","output":"3","explanation":"The answer is 'abc', with length 3."},{"input":"s = 'bbbbb'","output":"1","explanation":"The answer is 'b', with length 1."}],"constraints":["0 <= s.length <= 5 * 10^4","s consists of English letters, digits, symbols and spaces."],"python_solution":"class Solution:\n    def lengthOfLongestSubstring(self, s):","java_solution":"class Solution {\n    public int lengthOfLongestSubstring(String s) {\n    }\n}","test_cases":[{"input":"'abcabcbb'","expected":"3"},{"input":"'bbbbb'","expected":"1"}],"explanation":""},
    {"id":10,"title":"Minimum Window Substring","type":"Programming","category":"Sliding Window","difficulty":"Hard","companies":["Facebook","Google","Amazon","Uber"],"statement":"Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window.\n\nIf there is no such substring, return the empty string.","examples":[{"input":"s = 'ADOBECODEBANC', t = 'ABC'","output":"'BANC'","explanation":"The minimum window substring containing A, B, C is 'BANC'."}],"constraints":["m == s.length","n == t.length","1 <= m, n <= 10^5"],"python_solution":"class Solution:\n    def minWindow(self, s, t):","java_solution":"class Solution {\n    public String minWindow(String s, String t) {\n    }\n}","test_cases":[{"input":"'ADOBECODEBANC', 'ABC'","expected":"BANC"}],"explanation":""},

    # ===== STACK =====
    {"id":11,"title":"Valid Parentheses","type":"Programming","category":"Stack","difficulty":"Easy","companies":["Amazon","Microsoft","Facebook","Bloomberg"],"statement":"Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.","examples":[{"input":"s = '()'","output":"true","explanation":"Valid pair."},{"input":"s = '(]'","output":"false","explanation":"Mismatched brackets."}],"constraints":["1 <= s.length <= 10^4","s consists of parentheses only '()[]{}'."],"python_solution":"class Solution:\n    def isValid(self, s):","java_solution":"class Solution {\n    public boolean isValid(String s) {\n    }\n}","test_cases":[{"input":"'()'","expected":"True"},{"input":"'(]'","expected":"False"}],"explanation":""},
    {"id":12,"title":"Min Stack","type":"Programming","category":"Stack","difficulty":"Medium","companies":["Amazon","Microsoft","Bloomberg"],"statement":"Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.\n\nImplement the MinStack class with push, pop, top, and getMin methods.","examples":[{"input":"MinStack operations","output":"[null,null,null,-3,null,0,-2]","explanation":"Push -2, 0, -3, getMin returns -3, pop, top returns 0, getMin returns -2."}],"constraints":["Methods pop, top and getMin will always be called on non-empty stacks.","-2^31 <= val <= 2^31 - 1"],"python_solution":"class MinStack:\n    def __init__(self):\n    def push(self, val):\n    def pop(self):\n    def top(self):\n    def getMin(self):","java_solution":"class MinStack {\n    public MinStack() {}\n    public void push(int val) {}\n    public void pop() {}\n    public int top() { return 0; }\n    public int getMin() { return 0; }\n}","test_cases":[],"explanation":""},

    # ===== BINARY SEARCH =====
    {"id":13,"title":"Binary Search","type":"Programming","category":"Binary Search","difficulty":"Easy","companies":["Google","Microsoft"],"statement":"Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.\n\nYou must write an algorithm with O(log n) runtime complexity.","examples":[{"input":"nums = [-1,0,3,5,9,12], target = 9","output":"4","explanation":"9 exists in nums and its index is 4."},{"input":"nums = [-1,0,3,5,9,12], target = 2","output":"-1","explanation":"2 does not exist in nums."}],"constraints":["1 <= nums.length <= 10^4","All integers in nums are unique.","nums is sorted in ascending order."],"python_solution":"class Solution:\n    def search(self, nums, target):","java_solution":"class Solution {\n    public int search(int[] nums, int target) {\n    }\n}","test_cases":[{"input":"[-1,0,3,5,9,12], 9","expected":"4"},{"input":"[-1,0,3,5,9,12], 2","expected":"-1"}],"explanation":""},
    {"id":14,"title":"Search in Rotated Sorted Array","type":"Programming","category":"Binary Search","difficulty":"Medium","companies":["Amazon","Facebook","Microsoft","Google"],"statement":"There is an integer array nums sorted in ascending order (with distinct values). Prior to being passed to your function, nums is possibly rotated at an unknown pivot index.\n\nGiven the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.\n\nYou must write an algorithm with O(log n) runtime complexity.","examples":[{"input":"nums = [4,5,6,7,0,1,2], target = 0","output":"4","explanation":"0 is found at index 4."}],"constraints":["1 <= nums.length <= 5000","All values of nums are unique."],"python_solution":"class Solution:\n    def search(self, nums, target):","java_solution":"class Solution {\n    public int search(int[] nums, int target) {\n    }\n}","test_cases":[{"input":"[4,5,6,7,0,1,2], 0","expected":"4"},{"input":"[4,5,6,7,0,1,2], 3","expected":"-1"}],"explanation":""},
    {"id":15,"title":"Median of Two Sorted Arrays","type":"Programming","category":"Binary Search","difficulty":"Hard","companies":["Amazon","Google","Apple","Goldman Sachs"],"statement":"Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.\n\nThe overall run time complexity should be O(log (m+n)).","examples":[{"input":"nums1 = [1,3], nums2 = [2]","output":"2.0","explanation":"merged = [1,2,3], median is 2."},{"input":"nums1 = [1,2], nums2 = [3,4]","output":"2.5","explanation":"merged = [1,2,3,4], median is (2+3)/2 = 2.5."}],"constraints":["0 <= m <= 1000","0 <= n <= 1000","1 <= m + n <= 2000"],"python_solution":"class Solution:\n    def findMedianSortedArrays(self, nums1, nums2):","java_solution":"class Solution {\n    public double findMedianSortedArrays(int[] nums1, int[] nums2) {\n    }\n}","test_cases":[{"input":"[1,3], [2]","expected":"2.0"}],"explanation":""},

    # ===== LINKED LIST =====
    {"id":16,"title":"Reverse Linked List","type":"Programming","category":"Linked List","difficulty":"Easy","companies":["Amazon","Apple","Microsoft","Google"],"statement":"Given the head of a singly linked list, reverse the list, and return the reversed list.","examples":[{"input":"head = [1,2,3,4,5]","output":"[5,4,3,2,1]","explanation":"Reverse all links."}],"constraints":["The number of nodes in the list is the range [0, 5000].","-5000 <= Node.val <= 5000"],"python_solution":"class Solution:\n    def reverseList(self, head):","java_solution":"class Solution {\n    public ListNode reverseList(ListNode head) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":17,"title":"Merge Two Sorted Lists","type":"Programming","category":"Linked List","difficulty":"Easy","companies":["Amazon","Microsoft","Apple"],"statement":"You are given the heads of two sorted linked lists list1 and list2.\n\nMerge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.\n\nReturn the head of the merged linked list.","examples":[{"input":"list1 = [1,2,4], list2 = [1,3,4]","output":"[1,1,2,3,4,4]","explanation":"Merged in sorted order."}],"constraints":["Both lists are sorted in non-decreasing order."],"python_solution":"class Solution:\n    def mergeTwoLists(self, list1, list2):","java_solution":"class Solution {\n    public ListNode mergeTwoLists(ListNode list1, ListNode list2) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":18,"title":"Linked List Cycle","type":"Programming","category":"Linked List","difficulty":"Easy","companies":["Amazon","Microsoft","Google"],"statement":"Given head, the head of a linked list, determine if the linked list has a cycle in it.\n\nReturn true if there is a cycle, otherwise return false.","examples":[{"input":"head = [3,2,0,-4], pos = 1","output":"true","explanation":"Tail connects to node at index 1."}],"constraints":["The number of the nodes in the list is in the range [0, 10^4]."],"python_solution":"class Solution:\n    def hasCycle(self, head):","java_solution":"class Solution {\n    public boolean hasCycle(ListNode head) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":19,"title":"LRU Cache","type":"Programming","category":"Linked List / Design","difficulty":"Hard","companies":["Amazon","Google","Facebook","Microsoft","Apple"],"statement":"Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.\n\nImplement the LRUCache class:\n- LRUCache(int capacity) Initialize the LRU cache with positive size capacity.\n- int get(int key) Return the value of the key if it exists, otherwise return -1.\n- void put(int key, int value) Update the value if key exists. Otherwise, add the key-value pair. If the number of keys exceeds capacity, evict the least recently used key.","examples":[{"input":"LRUCache(2), put(1,1), put(2,2), get(1)","output":"1","explanation":"Cache stores {1:1, 2:2}, get(1) returns 1."}],"constraints":["1 <= capacity <= 3000","0 <= key <= 10^4","0 <= value <= 10^5"],"python_solution":"class LRUCache:\n    def __init__(self, capacity):\n    def get(self, key):\n    def put(self, key, value):","java_solution":"class LRUCache {\n    public LRUCache(int capacity) {}\n    public int get(int key) { return -1; }\n    public void put(int key, int value) {}\n}","test_cases":[],"explanation":""},

    # ===== TREES =====
    {"id":20,"title":"Invert Binary Tree","type":"Programming","category":"Trees","difficulty":"Easy","companies":["Google","Amazon"],"statement":"Given the root of a binary tree, invert the tree, and return its root.","examples":[{"input":"root = [4,2,7,1,3,6,9]","output":"[4,7,2,9,6,3,1]","explanation":"Left and right subtrees swapped at every node."}],"constraints":["The number of nodes in the tree is in the range [0, 100]."],"python_solution":"class Solution:\n    def invertTree(self, root):","java_solution":"class Solution {\n    public TreeNode invertTree(TreeNode root) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":21,"title":"Maximum Depth of Binary Tree","type":"Programming","category":"Trees","difficulty":"Easy","companies":["Amazon","Google","Microsoft"],"statement":"Given the root of a binary tree, return its maximum depth.\n\nA binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.","examples":[{"input":"root = [3,9,20,null,null,15,7]","output":"3","explanation":"The maximum depth is 3."}],"constraints":["The number of nodes in the tree is in the range [0, 10^4]."],"python_solution":"class Solution:\n    def maxDepth(self, root):","java_solution":"class Solution {\n    public int maxDepth(TreeNode root) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":22,"title":"Same Tree","type":"Programming","category":"Trees","difficulty":"Easy","companies":["Amazon","Microsoft"],"statement":"Given the roots of two binary trees p and q, write a function to check if they are the same or not.\n\nTwo binary trees are considered the same if they are structurally identical, and the nodes have the same value.","examples":[{"input":"p = [1,2,3], q = [1,2,3]","output":"true","explanation":"Both trees are identical."}],"constraints":["The number of nodes in both trees is in the range [0, 100]."],"python_solution":"class Solution:\n    def isSameTree(self, p, q):","java_solution":"class Solution {\n    public boolean isSameTree(TreeNode p, TreeNode q) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":23,"title":"Validate Binary Search Tree","type":"Programming","category":"Trees","difficulty":"Medium","companies":["Amazon","Facebook","Microsoft"],"statement":"Given the root of a binary tree, determine if it is a valid binary search tree (BST).\n\nA valid BST is defined as:\n- The left subtree contains only nodes with keys less than the node's key.\n- The right subtree contains only nodes with keys greater than the node's key.\n- Both the left and right subtrees must also be binary search trees.","examples":[{"input":"root = [2,1,3]","output":"true","explanation":"Valid BST."},{"input":"root = [5,1,4,null,null,3,6]","output":"false","explanation":"Root's right child is 4, which is less than 5."}],"constraints":["The number of nodes in the tree is in the range [1, 10^4]."],"python_solution":"class Solution:\n    def isValidBST(self, root):","java_solution":"class Solution {\n    public boolean isValidBST(TreeNode root) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":24,"title":"Lowest Common Ancestor of BST","type":"Programming","category":"Trees","difficulty":"Medium","companies":["Facebook","Amazon","Microsoft"],"statement":"Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.\n\nThe lowest common ancestor is the deepest node that has both p and q as descendants.","examples":[{"input":"root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8","output":"6","explanation":"The LCA of nodes 2 and 8 is 6."}],"constraints":["All Node.val are unique.","p != q","p and q will exist in the BST."],"python_solution":"class Solution:\n    def lowestCommonAncestor(self, root, p, q):","java_solution":"class Solution {\n    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":25,"title":"Binary Tree Level Order Traversal","type":"Programming","category":"Trees","difficulty":"Medium","companies":["Amazon","Facebook","Microsoft","Google"],"statement":"Given the root of a binary tree, return the level order traversal of its nodes' values (i.e., from left to right, level by level).","examples":[{"input":"root = [3,9,20,null,null,15,7]","output":"[[3],[9,20],[15,7]]","explanation":"Three levels of the tree."}],"constraints":["The number of nodes in the tree is in the range [0, 2000]."],"python_solution":"class Solution:\n    def levelOrder(self, root):","java_solution":"class Solution {\n    public List<List<Integer>> levelOrder(TreeNode root) {\n    }\n}","test_cases":[],"explanation":""},

    # ===== DYNAMIC PROGRAMMING =====
    {"id":26,"title":"Climbing Stairs","type":"Programming","category":"Dynamic Programming","difficulty":"Easy","companies":["Amazon","Apple","Google"],"statement":"You are climbing a staircase. It takes n steps to reach the top.\n\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?","examples":[{"input":"n = 2","output":"2","explanation":"1+1 or 2."},{"input":"n = 3","output":"3","explanation":"1+1+1, 1+2, 2+1."}],"constraints":["1 <= n <= 45"],"python_solution":"class Solution:\n    def climbStairs(self, n):","java_solution":"class Solution {\n    public int climbStairs(int n) {\n    }\n}","test_cases":[{"input":"2","expected":"2"},{"input":"3","expected":"3"}],"explanation":""},
    {"id":27,"title":"House Robber","type":"Programming","category":"Dynamic Programming","difficulty":"Medium","companies":["Amazon","Google","Cisco"],"statement":"You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. Adjacent houses have security systems connected, so you cannot rob two adjacent houses.\n\nGiven an integer array nums representing the amount at each house, return the maximum amount you can rob tonight.","examples":[{"input":"nums = [1,2,3,1]","output":"4","explanation":"Rob house 1 and house 3."},{"input":"nums = [2,7,9,3,1]","output":"12","explanation":"Rob house 1, 3, and 5."}],"constraints":["1 <= nums.length <= 100","0 <= nums[i] <= 400"],"python_solution":"class Solution:\n    def rob(self, nums):","java_solution":"class Solution {\n    public int rob(int[] nums) {\n    }\n}","test_cases":[{"input":"[1,2,3,1]","expected":"4"},{"input":"[2,7,9,3,1]","expected":"12"}],"explanation":""},
    {"id":28,"title":"Coin Change","type":"Programming","category":"Dynamic Programming","difficulty":"Medium","companies":["Amazon","Google","Apple","Goldman Sachs"],"statement":"You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.\n\nReturn the fewest number of coins needed to make up that amount. If it cannot be made up, return -1.","examples":[{"input":"coins = [1,2,5], amount = 11","output":"3","explanation":"11 = 5 + 5 + 1"},{"input":"coins = [2], amount = 3","output":"-1","explanation":"Cannot make 3 from coin 2."}],"constraints":["1 <= coins.length <= 12","1 <= coins[i] <= 2^31 - 1","0 <= amount <= 10^4"],"python_solution":"class Solution:\n    def coinChange(self, coins, amount):","java_solution":"class Solution {\n    public int coinChange(int[] coins, int amount) {\n    }\n}","test_cases":[{"input":"[1,2,5], 11","expected":"3"},{"input":"[2], 3","expected":"-1"}],"explanation":""},
    {"id":29,"title":"Longest Increasing Subsequence","type":"Programming","category":"Dynamic Programming","difficulty":"Medium","companies":["Amazon","Google","Microsoft"],"statement":"Given an integer array nums, return the length of the longest strictly increasing subsequence.","examples":[{"input":"nums = [10,9,2,5,3,7,101,18]","output":"4","explanation":"The longest increasing subsequence is [2,3,7,101]."}],"constraints":["1 <= nums.length <= 2500","-10^4 <= nums[i] <= 10^4"],"python_solution":"class Solution:\n    def lengthOfLIS(self, nums):","java_solution":"class Solution {\n    public int lengthOfLIS(int[] nums) {\n    }\n}","test_cases":[{"input":"[10,9,2,5,3,7,101,18]","expected":"4"}],"explanation":""},
    {"id":30,"title":"Longest Common Subsequence","type":"Programming","category":"Dynamic Programming","difficulty":"Medium","companies":["Amazon","Google","Microsoft"],"statement":"Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.\n\nA subsequence is generated from the original string with some characters deleted without changing the relative order.","examples":[{"input":"text1 = 'abcde', text2 = 'ace'","output":"3","explanation":"The longest common subsequence is 'ace'."}],"constraints":["1 <= text1.length, text2.length <= 1000","text1 and text2 consist of only lowercase English characters."],"python_solution":"class Solution:\n    def longestCommonSubsequence(self, text1, text2):","java_solution":"class Solution {\n    public int longestCommonSubsequence(String text1, String text2) {\n    }\n}","test_cases":[{"input":"'abcde', 'ace'","expected":"3"},{"input":"'abc', 'def'","expected":"0"}],"explanation":""},
    {"id":31,"title":"Word Break","type":"Programming","category":"Dynamic Programming","difficulty":"Medium","companies":["Amazon","Facebook","Google","Bloomberg"],"statement":"Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.","examples":[{"input":"s = 'leetcode', wordDict = ['leet','code']","output":"true","explanation":"'leetcode' can be segmented as 'leet code'."}],"constraints":["1 <= s.length <= 300","1 <= wordDict.length <= 1000"],"python_solution":"class Solution:\n    def wordBreak(self, s, wordDict):","java_solution":"class Solution {\n    public boolean wordBreak(String s, List<String> wordDict) {\n    }\n}","test_cases":[{"input":"'leetcode', ['leet', 'code']","expected":"True"}],"explanation":""},

    # ===== BACKTRACKING =====
    {"id":32,"title":"Subsets","type":"Programming","category":"Backtracking","difficulty":"Medium","companies":["Amazon","Facebook","Google"],"statement":"Given an integer array nums of unique elements, return all possible subsets (the power set).\n\nThe solution set must not contain duplicate subsets. Return the solution in any order.","examples":[{"input":"nums = [1,2,3]","output":"[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]","explanation":"All 8 possible subsets."}],"constraints":["1 <= nums.length <= 10","All the numbers of nums are unique."],"python_solution":"class Solution:\n    def subsets(self, nums):","java_solution":"class Solution {\n    public List<List<Integer>> subsets(int[] nums) {\n    }\n}","test_cases":[{"input":"[0]","expected":"[[], [0]]"}],"explanation":""},
    {"id":33,"title":"Combination Sum","type":"Programming","category":"Backtracking","difficulty":"Medium","companies":["Amazon","Microsoft","Facebook"],"statement":"Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target.\n\nThe same number may be chosen an unlimited number of times.","examples":[{"input":"candidates = [2,3,6,7], target = 7","output":"[[2,2,3],[7]]","explanation":"2 + 2 + 3 = 7 and 7 = 7."}],"constraints":["1 <= candidates.length <= 30","All elements of candidates are distinct.","1 <= target <= 40"],"python_solution":"class Solution:\n    def combinationSum(self, candidates, target):","java_solution":"class Solution {\n    public List<List<Integer>> combinationSum(int[] candidates, int target) {\n    }\n}","test_cases":[{"input":"[2], 1","expected":"[]"}],"explanation":""},
    {"id":34,"title":"Permutations","type":"Programming","category":"Backtracking","difficulty":"Medium","companies":["Amazon","Facebook","Microsoft"],"statement":"Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.","examples":[{"input":"nums = [1,2,3]","output":"[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]","explanation":"All 6 permutations."}],"constraints":["1 <= nums.length <= 6","All the integers of nums are unique."],"python_solution":"class Solution:\n    def permute(self, nums):","java_solution":"class Solution {\n    public List<List<Integer>> permute(int[] nums) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":35,"title":"Word Search","type":"Programming","category":"Backtracking","difficulty":"Medium","companies":["Amazon","Microsoft","Bloomberg"],"statement":"Given an m x n grid of characters board and a string word, return true if word exists in the grid.\n\nThe word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same cell may not be used more than once.","examples":[{"input":"board = [['A','B','C','E'],['S','F','C','S'],['A','D','E','E']], word = 'ABCCED'","output":"true","explanation":"Path exists."}],"constraints":["m == board.length","n = board[i].length","1 <= m, n <= 6"],"python_solution":"class Solution:\n    def exist(self, board, word):","java_solution":"class Solution {\n    public boolean exist(char[][] board, String word) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":36,"title":"N-Queens","type":"Programming","category":"Backtracking","difficulty":"Hard","companies":["Amazon","Google","Microsoft"],"statement":"The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.\n\nGiven an integer n, return the number of distinct solutions to the n-queens puzzle.","examples":[{"input":"n = 4","output":"2","explanation":"There are 2 distinct solutions."}],"constraints":["1 <= n <= 9"],"python_solution":"class Solution:\n    def totalNQueens(self, n):","java_solution":"class Solution {\n    public int totalNQueens(int n) {\n    }\n}","test_cases":[{"input":"4","expected":"2"},{"input":"1","expected":"1"}],"explanation":""},

    # ===== GRAPHS =====
    {"id":37,"title":"Number of Islands","type":"Programming","category":"Graphs","difficulty":"Medium","companies":["Amazon","Microsoft","Google","Facebook"],"statement":"Given an m x n 2D binary grid which represents a map of '1's (land) and '0's (water), return the number of islands.\n\nAn island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.","examples":[{"input":"grid = [['1','1','0'],['0','1','0'],['0','0','1']]","output":"2","explanation":"Two separate islands."}],"constraints":["m == grid.length","n == grid[i].length","1 <= m, n <= 300"],"python_solution":"class Solution:\n    def numIslands(self, grid):","java_solution":"class Solution {\n    public int numIslands(char[][] grid) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":38,"title":"Clone Graph","type":"Programming","category":"Graphs","difficulty":"Medium","companies":["Facebook","Google","Amazon"],"statement":"Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph.\n\nEach node in the graph contains a value and a list of its neighbors.","examples":[{"input":"adjList = [[2,4],[1,3],[2,4],[1,3]]","output":"[[2,4],[1,3],[2,4],[1,3]]","explanation":"Deep clone of the graph."}],"constraints":["The number of nodes is in the range [0, 100].","1 <= Node.val <= 100","Node.val is unique."],"python_solution":"class Solution:\n    def cloneGraph(self, node):","java_solution":"class Solution {\n    public Node cloneGraph(Node node) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":39,"title":"Course Schedule","type":"Programming","category":"Graphs","difficulty":"Medium","companies":["Amazon","Facebook","Google","Microsoft"],"statement":"There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai.\n\nReturn true if you can finish all courses. Otherwise, return false.","examples":[{"input":"numCourses = 2, prerequisites = [[1,0]]","output":"true","explanation":"Take course 0 then course 1."},{"input":"numCourses = 2, prerequisites = [[1,0],[0,1]]","output":"false","explanation":"Circular dependency."}],"constraints":["1 <= numCourses <= 2000","0 <= prerequisites.length <= 5000"],"python_solution":"class Solution:\n    def canFinish(self, numCourses, prerequisites):","java_solution":"class Solution {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n    }\n}","test_cases":[{"input":"2, [[1,0]]","expected":"True"},{"input":"2, [[1,0],[0,1]]","expected":"False"}],"explanation":""},

    # ===== INTERVALS =====
    {"id":40,"title":"Merge Intervals","type":"Programming","category":"Intervals","difficulty":"Medium","companies":["Amazon","Facebook","Google","Microsoft"],"statement":"Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals.","examples":[{"input":"intervals = [[1,3],[2,6],[8,10],[15,18]]","output":"[[1,6],[8,10],[15,18]]","explanation":"Intervals [1,3] and [2,6] overlap, merged into [1,6]."}],"constraints":["1 <= intervals.length <= 10^4"],"python_solution":"class Solution:\n    def merge(self, intervals):","java_solution":"class Solution {\n    public int[][] merge(int[][] intervals) {\n    }\n}","test_cases":[{"input":"[[1,4],[4,5]]","expected":"[[1, 5]]"}],"explanation":""},
    {"id":41,"title":"Meeting Rooms","type":"Programming","category":"Intervals","difficulty":"Easy","companies":["Amazon","Facebook","Bloomberg"],"statement":"Given an array of meeting time intervals where intervals[i] = [starti, endi], determine if a person could attend all meetings.","examples":[{"input":"intervals = [[0,30],[5,10],[15,20]]","output":"false","explanation":"Meetings overlap."},{"input":"intervals = [[7,10],[2,4]]","output":"true","explanation":"No overlap."}],"constraints":["0 <= intervals.length <= 10^4"],"python_solution":"class Solution:\n    def canAttendMeetings(self, intervals):","java_solution":"class Solution {\n    public boolean canAttendMeetings(int[][] intervals) {\n    }\n}","test_cases":[{"input":"[[0,30],[5,10],[15,20]]","expected":"False"},{"input":"[[7,10],[2,4]]","expected":"True"}],"explanation":""},

    # ===== GREEDY =====
    {"id":42,"title":"Jump Game","type":"Programming","category":"Greedy","difficulty":"Medium","companies":["Amazon","Google","Microsoft"],"statement":"You are given an integer array nums. You are initially positioned at the array's first index, and each element represents your maximum jump length at that position.\n\nReturn true if you can reach the last index, or false otherwise.","examples":[{"input":"nums = [2,3,1,1,4]","output":"true","explanation":"Jump 1 step from index 0 to 1, then 3 steps to end."},{"input":"nums = [3,2,1,0,4]","output":"false","explanation":"Stuck at index 3."}],"constraints":["1 <= nums.length <= 10^4","0 <= nums[i] <= 10^5"],"python_solution":"class Solution:\n    def canJump(self, nums):","java_solution":"class Solution {\n    public boolean canJump(int[] nums) {\n    }\n}","test_cases":[{"input":"[2,3,1,1,4]","expected":"True"},{"input":"[3,2,1,0,4]","expected":"False"}],"explanation":""},

    # ===== HEAP / PRIORITY QUEUE =====
    {"id":43,"title":"Kth Largest Element in an Array","type":"Programming","category":"Heap","difficulty":"Medium","companies":["Amazon","Facebook","Google","Microsoft"],"statement":"Given an integer array nums and an integer k, return the kth largest element in the array.\n\nNote that it is the kth largest element in the sorted order, not the kth distinct element.","examples":[{"input":"nums = [3,2,1,5,6,4], k = 2","output":"5","explanation":"The 2nd largest element is 5."},{"input":"nums = [3,2,3,1,2,4,5,5,6], k = 4","output":"4","explanation":"The 4th largest element is 4."}],"constraints":["1 <= k <= nums.length <= 10^5","-10^4 <= nums[i] <= 10^4"],"python_solution":"class Solution:\n    def findKthLargest(self, nums, k):","java_solution":"class Solution {\n    public int findKthLargest(int[] nums, int k) {\n    }\n}","test_cases":[{"input":"[3,2,1,5,6,4], 2","expected":"5"}],"explanation":""},
    {"id":44,"title":"Top K Frequent Elements","type":"Programming","category":"Heap","difficulty":"Medium","companies":["Amazon","Facebook","Google","Apple"],"statement":"Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.","examples":[{"input":"nums = [1,1,1,2,2,3], k = 2","output":"[1,2]","explanation":"1 appears 3 times, 2 appears 2 times."}],"constraints":["1 <= nums.length <= 10^5","-10^4 <= nums[i] <= 10^4","k is in the range [1, number of unique elements]."],"python_solution":"class Solution:\n    def topKFrequent(self, nums, k):","java_solution":"class Solution {\n    public int[] topKFrequent(int[] nums, int k) {\n    }\n}","test_cases":[{"input":"[1,1,1,2,2,3], 2","expected":"[1, 2]"}],"explanation":""},

    # ===== TRIE =====
    {"id":45,"title":"Implement Trie (Prefix Tree)","type":"Programming","category":"Trie","difficulty":"Medium","companies":["Amazon","Google","Microsoft"],"statement":"A trie (pronounced 'try') or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings.\n\nImplement the Trie class with insert, search, and startsWith methods.","examples":[{"input":"Trie operations: insert('apple'), search('apple'), startsWith('app')","output":"[null, true, true]","explanation":"Insert apple, search finds it, prefix 'app' exists."}],"constraints":["1 <= word.length, prefix.length <= 2000","word and prefix consist only of lowercase English letters."],"python_solution":"class Trie:\n    def __init__(self):\n    def insert(self, word):\n    def search(self, word):\n    def startsWith(self, prefix):","java_solution":"class Trie {\n    public Trie() {}\n    public void insert(String word) {}\n    public boolean search(String word) { return false; }\n    public boolean startsWith(String prefix) { return false; }\n}","test_cases":[],"explanation":""},

    # ===== BIT MANIPULATION =====
    {"id":46,"title":"Number of 1 Bits","type":"Programming","category":"Bit Manipulation","difficulty":"Easy","companies":["Apple","Microsoft"],"statement":"Write a function that takes the binary representation of a positive integer and returns the number of set bits it has (also known as the Hamming weight).","examples":[{"input":"n = 11","output":"3","explanation":"11 in binary is 1011, which has three set bits."}],"constraints":["1 <= n <= 2^31 - 1"],"python_solution":"class Solution:\n    def hammingWeight(self, n):","java_solution":"class Solution {\n    public int hammingWeight(int n) {\n    }\n}","test_cases":[{"input":"11","expected":"3"}],"explanation":""},
    {"id":47,"title":"Counting Bits","type":"Programming","category":"Bit Manipulation","difficulty":"Easy","companies":["Amazon","Google"],"statement":"Given an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1's in the binary representation of i.","examples":[{"input":"n = 2","output":"[0,1,1]","explanation":"0 -> 0, 1 -> 1, 2 -> 10."},{"input":"n = 5","output":"[0,1,1,2,1,2]","explanation":"Binary representations of 0 through 5."}],"constraints":["0 <= n <= 10^5"],"python_solution":"class Solution:\n    def countBits(self, n):","java_solution":"class Solution {\n    public int[] countBits(int n) {\n    }\n}","test_cases":[{"input":"2","expected":"[0, 1, 1]"},{"input":"5","expected":"[0, 1, 1, 2, 1, 2]"}],"explanation":""},
    {"id":48,"title":"Reverse Bits","type":"Programming","category":"Bit Manipulation","difficulty":"Easy","companies":["Apple","Amazon"],"statement":"Reverse bits of a given 32 bits unsigned integer.","examples":[{"input":"n = 43261596","output":"964176192","explanation":"Binary: 00000010100101000001111010011100 -> 00111001011110000010100101000000"}],"constraints":["The input must be a binary string of length 32."],"python_solution":"class Solution:\n    def reverseBits(self, n):","java_solution":"class Solution {\n    public int reverseBits(int n) {\n    }\n}","test_cases":[{"input":"43261596","expected":"964176192"}],"explanation":""},

    # ===== MATH & GEOMETRY =====
    {"id":49,"title":"Rotate Image","type":"Programming","category":"Math & Geometry","difficulty":"Medium","companies":["Amazon","Google","Microsoft","Apple"],"statement":"You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).\n\nYou have to rotate the image in-place, which means you have to modify the input 2D matrix directly.","examples":[{"input":"matrix = [[1,2,3],[4,5,6],[7,8,9]]","output":"[[7,4,1],[8,5,2],[9,6,3]]","explanation":"Matrix rotated 90 degrees clockwise."}],"constraints":["n == matrix.length == matrix[i].length","1 <= n <= 20"],"python_solution":"class Solution:\n    def rotate(self, matrix):","java_solution":"class Solution {\n    public void rotate(int[][] matrix) {\n    }\n}","test_cases":[],"explanation":""},
    {"id":50,"title":"Spiral Matrix","type":"Programming","category":"Math & Geometry","difficulty":"Medium","companies":["Amazon","Microsoft","Google","Apple"],"statement":"Given an m x n matrix, return all elements of the matrix in spiral order.","examples":[{"input":"matrix = [[1,2,3],[4,5,6],[7,8,9]]","output":"[1,2,3,6,9,8,7,4,5]","explanation":"Elements traversed in spiral order."}],"constraints":["m == matrix.length","n == matrix[i].length","1 <= m, n <= 10"],"python_solution":"class Solution:\n    def spiralOrder(self, matrix):","java_solution":"class Solution {\n    public List<Integer> spiralOrder(int[][] matrix) {\n    }\n}","test_cases":[{"input":"[[1,2,3],[4,5,6],[7,8,9]]","expected":"[1, 2, 3, 6, 9, 8, 7, 4, 5]"}],"explanation":""}
]

with open('dataset/questions.json', 'w', encoding='utf-8') as f:
    json.dump(questions, f, indent=2)

print(f"Generated {len(questions)} real interview questions!")
categories = {}
for q in questions:
    cat = q['category']
    categories[cat] = categories.get(cat, 0) + 1
for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
    print(f"  {cat}: {count} questions")
