import React, { Suspense } from 'react';
import AuthForm from '@/components/features/auth-form';
import { Loader2 } from 'lucide-react';

export const metadata = {
  title: "PrepForge AI | Authenticate",
  description: "Secure login and signup portal for PrepForge AI platform.",
};

export default function AuthPage() {
  return (
    <main className="min-h-screen grid grid-cols-1 lg:grid-cols-12 bg-background relative overflow-hidden font-sans">
      {/* Decorative Atmosphere Glows */}
      <div className="absolute top-[-10%] left-[-10%] w-[400px] h-[400px] bg-primary/5 rounded-full blur-[100px] pointer-events-none"></div>
      <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] bg-secondary/5 rounded-full blur-[120px] pointer-events-none"></div>

      {/* Left Column: Branding (Large screens only) */}
      <section className="hidden lg:flex lg:col-span-6 flex-col justify-between p-2xl bg-surface-container-low border-r border-outline-variant/20 relative overflow-hidden">
        {/* Background Subtle Gradient Overlay */}
        <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent opacity-80 z-10"></div>
        <div 
          className="absolute inset-0 bg-cover bg-center opacity-10"
          style={{ backgroundImage: `url('/images/auth-illustration.jpg')` }}
        />

        {/* Top Branding Logo */}
        <div className="relative z-20 flex items-center gap-md">
          <img 
            src="/images/logo.png" 
            alt="PrepForge Logo" 
            className="w-10 h-10 rounded-lg shadow-lg shadow-primary/10 border border-primary/20"
          />
          <h1 className="font-headline-sm text-headline-sm text-primary font-black tracking-tighter">
            PrepForge AI
          </h1>
        </div>

        {/* Mid Hero Panel */}
        <div className="relative z-20 space-y-lg max-w-lg">
          <div className="glass-panel p-xl rounded-2xl border-t border-primary/10 space-y-md shadow-2xl">
            <h2 className="text-display-lg-mobile font-bold tracking-tight text-on-surface">
              Master the <span className="ai-gradient-text">FAANG</span> Interview Bar
            </h2>
            <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
              Unlock architectural playgrounds, custom evaluation test cases, and real-time conceptual feedback generated by our fine-tuned coding models.
            </p>
          </div>
        </div>

        {/* Bottom Social Proof */}
        <div className="relative z-20 flex items-center gap-md">
          <div className="flex -space-x-sm">
            <img className="w-8 h-8 rounded-full border-2 border-surface object-cover" src="/images/alex-rivera.jpg" alt="User 1" />
            <img className="w-8 h-8 rounded-full border-2 border-surface object-cover" src="/images/user-avatar.jpg" alt="User 2" />
            <img className="w-8 h-8 rounded-full border-2 border-surface object-cover" src="/images/user-avatar-2.jpg" alt="User 3" />
          </div>
          <p className="font-body-sm text-body-sm text-on-surface-variant">
            Join <span className="text-primary font-bold">12,000+</span> software engineers crafting code.
          </p>
        </div>
      </section>

      {/* Right Column: Form Container */}
      <section className="col-span-1 lg:col-span-6 flex flex-col justify-center items-center p-md md:p-2xl relative z-20">
        <Suspense fallback={
          <div className="glass-panel w-full max-w-[480px] p-xl rounded-xl flex flex-col items-center justify-center space-y-md min-h-[450px]">
            <Loader2 className="w-8 h-8 text-primary animate-spin" />
            <p className="text-body-sm text-on-surface-variant animate-pulse">Setting up secure gates...</p>
          </div>
        }>
          <AuthForm />
        </Suspense>

        {/* Footer info below card */}
        <div className="mt-xl text-center text-xs text-on-surface-variant/40 max-w-sm">
          By signing in, you agree to PrepForge AI&apos;s standard security policies and local data storage terms.
        </div>
      </section>
    </main>
  );
}
